## **Copy() and View() :**

In [1]:
import numpy as np

In [11]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = x.copy()
x[0] = 19
print(x)

[19  2  3  4  5  6  7  8  9]


In [12]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = x.copy()
x[0] = 19
print(y)

[1 2 3 4 5 6 7 8 9]


In [13]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = x.view()
x[0] = 19
print(x)

[19  2  3  4  5  6  7  8  9]


In [15]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = x.view()
x[0] = 19
print(y)

[19  2  3  4  5  6  7  8  9]
