# **Indexing Array:**

In [1]:
import numpy as np

In [21]:
import numpy as np
x = np.array([1,2,3])
print(x[0])

1


In [24]:
#  1-Dimensions array:
y =np.array(["Hello ",2,"World"])
print(y[0] + y[2])

Hello World


In [25]:
y = np.array(["Hello ",2,"World"])
z = y[0] + y[2]
print(z)


Hello World


In [27]:
# 2-Dimensions array:
C = np.array([[1,2,3]])
print(C[0])



[1 2 3]


In [29]:
# 2-Dimensions array:
D = np.array([[1,2,3],[4,5,6]])
print(D[0])
print(D[1])
print(D[0,0])
print(D[1,2])

[1 2 3]
[4 5 6]
1
6


In [32]:
# 3-Dimensions array:[0,0,0]
E = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(E[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
E = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(E[0,0])
print(E[0,0,1])

[1 2 3]
2


In [35]:
E = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(E[0,1,1])
print(E[0,2,1])
print(E[0,-1])
print(E[0,-1,-1])

5
8
[7 8 9]
9
