## ** Iterating :**

In [ ]:
import numpy as np

In [31]:
x = np.array([1,2,3,4,5,6,7,8,9])
for y in x:
 print(y)

1
2
3
4
5
6
7
8
9


In [32]:
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for y in x:
 print(y)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [34]:
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for x in A:
  for y in x:
   print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
F = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in F:
  print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
F = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in F:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9


In [40]:
# nditer():
F = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(F):
 print(x)

1
2
3
4
5
6
7
8
9


In [41]:
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in np.nditer(D,flags=['buffered'],op_dtypes=['S']):
 print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [43]:
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for x in np.nditer(A[: ,: :2]):
  print(x)

1
3
5
7
9
11


In [44]:
# ndenumerate()
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for x in np.ndenumerate(A):
  print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((0, 5), 6)
((1, 0), 7)
((1, 1), 8)
((1, 2), 9)
((1, 3), 10)
((1, 4), 11)
((1, 5), 12)


In [46]:
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
for idx,x in np.ndenumerate(A):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(0, 5) 6
(1, 0) 7
(1, 1) 8
(1, 2) 9
(1, 3) 10
(1, 4) 11
(1, 5) 12
