## **Shape and Reshape :**

In [1]:
import numpy as np

In [16]:
D = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(D.shape)

(2, 6)


In [17]:
x = np.array([1,2,3,4,5,6,7,8,9],ndmin=5)
print(x)
print(x.shape)

[[[[[1 2 3 4 5 6 7 8 9]]]]]
(1, 1, 1, 1, 9)


In [18]:
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
E = D.reshape(4,3)
print(E)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
E = D.reshape(2,3,2)
print(E)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
E = D.reshape(2,3,2).base
print(E)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
# unknow Dimension
D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
E = D.reshape(2,2,-1)
print(E)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
F = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
G = F.reshape(-1)
print(F)
print(G)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3 4 5 6 7 8 9]
