# **NumPy Array Slicing:**


Syntax : [Start:End], [Start:End:Step]

In [1]:
import numpy as np

In [38]:
# 1-Dimensions array:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[1:3])

[2 3]


In [40]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[1:6:3])

[2 5]


In [43]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[:])
print(x[:-8])
print(x[-3:-1])

[1 2 3 4 5 6 7 8 9]
[1]
[7 8]


In [59]:
# 2-Dimensions array:
D = np.array([[1,2,3],[4,5,6]])
print(D[0,:6])

[1 2 3]


In [60]:
D = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(D[0, 1:3])
print(D[0,:2])
print(D[1, 2:3])

[2 3]
[1 2]
[9]


In [64]:
D = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(D[0:2,1:4])

[[ 2  3  4]
 [ 8  9 10]]
